# Generated by Django 5.0.2 on 2024-03-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='body_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_uz',
        ),
    ]
